default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: gharmon
  password: 

development:
  <<: *default
  database: pizza_app_development

test:
  <<: *default
  database: pizza_app_test

# Use DATABASE_URL in deployed environments.

